package application

var (
	PROPERTY_NAME_GURMS_AI_SERVING_HOME = "GURMS_AI_SERVING_HOME"
	PROPERTY_NAME_GURMS_GATEWAY_HOME    = "GURMS_GATEWAY_HOME"
	PROPERTY_NAME_GURMS_SERVICE_HOME    = "GURMS_SERVICE_HOME"
	PROPERTY_NAME_GURMS_MOCK_NODE_HOME  = "GURMS_MOCK_NODE_HOME"
)
