package application

const (
	CLOSE_FAKE_CLIENTS = iota
	CLOSE_SESSIONS

	CLOSE_GATEWAY_UDP_SERVER
	CLOSE_GATEWAY_TCP_SERVER
	CLOSE_GATEWAY_WEBSOCKET_SERVER
	CLOSE_ADMIN_SERVER

	CLOSE_BLOCKLIST
	CLOSE_NODE
	CLOSE_PUSH_NOTIFICATION
	CLOSE_PLUGINS

	CLOSE_REDIS_CONNECTIONS
	CLOSE_MONGODB_CONNECTIONS

	CLOSE_LOG_PROCESSOR
)
