package impl

const (
	PRIMITVE_BYTE = iota + 1
	PRIMITIVE_INT16
	PRIMITIVE_INT
	PRIMITIVE_INT64
	PRIMITIVE_FLOAT32
	PRIMITIVE_FLOAT64
	PRIMITIVE_RUNE
	PRIMITIVE_BOOL

	STRING = 10

	BO_USER_ONLIN_INFO = 200
	BO_USER_SESSIONS   = 201

	// RPC Common
	RPC_ERROR = 1000
	// RPC Connection
	RPC_OPENING_HANDSHAKE = 1100
	RPC_CLOSING_HANDSHAKE = 1101
	RPC_KEEPALIVE         = 1102
	// RPC Request/Notification
	RPC_HANDLE_SERVICE_REQUEST = 1200
	RPC_SENC_NOTIFICATION      = 1201
	// RPC Business
	RPC_QUERY_USER_SESSIONS       = 1300
	RPC_SET_USER_OFFLINE          = 1301
	RPC_UPDATE_ONLINE_USER_STATUS = 1302
	RPC_CREATE_USER               = 1303
	// RPC Statistics
	RPC_COUNT_ONLINE_USERS = 1400

	DTO_SERVICE_RESPONSE = 2000
)

func getTypeById() {}
